# Generated by Django 2.2.12 on 2020-05-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgdh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gxfghtgf',
            name='asrgfwfsc',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gxfghtgf',
            name='erfr',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gxfghtgf',
            name='ewfergftr',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gxfghtgf',
            name='gujuykju',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gxfghtgf',
            name='qsqsw',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gxfghtgf',
            name='sdferg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gxfghtgf',
            name='werfe',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
