# Generated by Django 2.2.12 on 2020-05-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgnbfhvc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgjf',
            name='dewdwee',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tgjf',
            name='efrfrfrf',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tgjf',
            name='erett',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tgjf',
            name='erfrgth',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tgjf',
            name='ikiol',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tgjf',
            name='qwsqwswqq',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tgjf',
            name='safasdf',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tgjf',
            name='sdasf',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tgjf',
            name='tyjyuj',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tgjf',
            name='wdwdwe',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
