# Generated by Django 2.2.12 on 2020-05-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20200504_0604"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usersfg",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yufgh", models.BigIntegerField()),
            ],
        ),
    ]
